// src/types/candle.types.ts
/** Raw OHLCV candle from Twelve Data API or fallback generator */
export interface Candle {
  open: number
  high: number
  low: number
  close: number
  datetime: string
  /** True when this candle was generated by the fallback simulator */
  simulated?: boolean
}

export interface CandleCache {
  candles: Record<string, Candle[]>
  fetchedAt: Record<string, number>
}
